<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>StockApi</RootNamespace>
    <AssemblyName>StockApi</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\StoredProcedures\StockItem\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\StoredProcedures\StockOrder\*.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <!--This tells MSBuild: when you build, copy these .sql files from the project folder into the output folder (bin/Debug/net8.0/).-->
    <!--add the StockOrder copy rule in StockApi.csproj so those scripts land in bin/ on build, so EnsureStockOrderStoredProcedures() can find them at startup.-->
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="StockApi.Tests/**" />
    <None Remove="StockApi.Tests/**" />
    <EmbeddedResource Remove="StockApi.Tests/**" />
    <Content Remove="StockApi.Tests/**" />
    <Compile Remove="StockApi.Test.IntegrationTests/**" />
    <None Remove="StockApi.Test.IntegrationTests/**" />
    <EmbeddedResource Remove="StockApi.Test.IntegrationTests/**" />
    <Content Remove="StockApi.Test.IntegrationTests/**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="StockApi.Tests" />
    <InternalsVisibleTo Include="StockApi.Test.IntegrationTests" />
  </ItemGroup>

</Project>
